### ISSUE TITLE
之前的Leetcode GO没有了吗？

### ISSUE THREAD

**Issue by jaykangta** [aQuaYi/Go-Notes#1]
求。

**Comment by aQuaYi** [comment]
我也是才发现的。
谢谢提醒。

Repository unavailable due to DMCA takedown.
This repository is currently disabled due to a DMCA takedown notice. We have disabled public access to the repository. The notice has been publicly posted.

If you are the repository owner, and you believe that your repository was disabled as a result of mistake or misidentification, you have the right to file a counter notice and have the repository reinstated. Our help articles provide more details on our DMCA takedown policy and how to file a counter notice. If you have any questions about the process or the risks in filing a counter notice, we suggest that you consult with a lawyer.

**Comment by jaykangta** [comment]
所以还有吗？

**Comment by aQuaYi** [comment]
我正在申述。
你想看哪一题，我　ｃｏｐｙ　给你呀！
电脑上还有备份。

**Comment by jaykangta** [comment]
我其实在练习Go，所以刷一刷Leetcode，没有具体到哪儿一个题，不知道可否都发给我呢，感觉每次一个题一个题麻烦您也不好。 或者您可以选择其他地方来存放？

**Comment by aQuaYi** [comment]
https://github.com/aQuaYi/LeetCode-in-Golang
新开的
